feat: реализовать логику работы приложения согласно ТЗ15
VIashunin/java-shareit pull request #3
Opened 2023-06-17 13:26 UTC by VIashunin

2023-06-18 18:26 UTC, Fleaman777 requested changes

2023-06-18 18:26 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
>          Booking booking = bookingRepository.getBookingByBookerIdAndItemId(userId, itemId, LocalDateTime.now());
LocalDateTime.now() можно было бы вынести в локальную перменную, что бы не дублировать получение текущей даты

2023-06-18 18:26 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    ItemRequestDto addRequest(@RequestHeader(X_SHARER_USER_ID) long userId, @Valid @RequestBody ItemRequestDto itemRequestDto) {
лучше проставить модификтора доступа public, 
на 1й взгляд может показаться, что и так работает, 
но что там внтури у спринга до конца не известно, и возможно какой-то функционал не будет работать

2023-06-18 18:26 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto addRequest(long userId, ItemRequestDto itemRequestDto) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции,

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.item", notNullValue()));
можно вынести общую логику проверки ответов в отдельный метод, чтобы уменьшить дублирование кода.

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @BeforeAll
@BeforeAll используется для статической инициализации данных, и она выполняется один раз перед всеми тестами. Если какой-то из твоих тестов модифицирует эти данные, это может повлиять на другие тесты, поскольку они используют общие данные. Рассмотри возможность использования @BeforeEach, чтобы инициализировать данные перед каждым тестом.

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 1L))
X-Sharer-User-Id в тестах так же можно было бы вынести в константу

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingDataJpaTest.java
> +        MatcherAssert.assertThat(bookingJpa.getStart(), equalTo(booking.getStart()));
я бы посоветовал бы использовать AssertJ вместо MatcherAssert, 
AssertJ  более гибкая и читаемая библиотека

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingDataJpaTest.java
> +        MatcherAssert.assertThat(bookingJpaList.get(0).getBookingStatus(), equalTo(booking.getBookingStatus()));
здесь так же часть проверки совпадает с проверками в других методах, хорошо это было бы вынести в отдельный метод, что бы избежать дублирования

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        ReflectionTestUtils.setField(bookingService, "itemService", itemService);
что ты пытаешься сделать при помощи ReflectionTestUtils ? 
я думаю это можно было бы сделать через обычные способы типа Mock, MockBean или @Autowire

по сути ReflectionTestUtils добавляет скрытую логику, что конечно может в будушем доабвить проблем

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +}
есть общие вещи которе можно было бы вынести в отдельные методы или в метод с аннотацией @BeforeEach, 

это позволит сократить дублирование, DRY принцип в программировании 

относится ко всем аналогичным местам в других тестах

2023-06-18 18:26 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +        UserDto userDto = UserDto.builder().id(1L).name("User").email("user@yandex.ru").build();
например этот юзер можно вынести в метод c аннотацией @BeforeEach

2023-06-19 15:28 UTC, VIashunin commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
>          Booking booking = bookingRepository.getBookingByBookerIdAndItemId(userId, itemId, LocalDateTime.now());
Вынес LocalDateTime.now() в локальную переменную

2023-06-19 15:32 UTC, VIashunin commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    ItemRequestDto addRequest(@RequestHeader(X_SHARER_USER_ID) long userId, @Valid @RequestBody ItemRequestDto itemRequestDto) {
добавил модификаторы доступа public в контроллеры BookingController и ItemRequestController

2023-06-19 16:02 UTC, VIashunin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto addRequest(long userId, ItemRequestDto itemRequestDto) {
Над классом стоит аннотация @Transactional. Этого не достаточно?

2023-06-19 18:14 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.item", notNullValue()));
вынес дублирующую логику в отдельные методы

2023-06-19 18:16 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @BeforeAll
Заменил @BeforeAll на @BeforeEach

2023-06-19 18:18 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 1L))
X-Sharer-User-Id вынес в константу

2023-06-19 18:28 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingDataJpaTest.java
> +        MatcherAssert.assertThat(bookingJpa.getStart(), equalTo(booking.getStart()));
Спасибо большое за совет! в будущих проектах буду использовать библиотеку AssertJ

2023-06-19 18:38 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingDataJpaTest.java
> +        MatcherAssert.assertThat(bookingJpaList.get(0).getBookingStatus(), equalTo(booking.getBookingStatus()));
вынес дублирующий код в отдельный метод

2023-06-19 18:51 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        ReflectionTestUtils.setField(bookingService, "itemService", itemService);
Здесь я использовал пример из теории:
![image](https://github.com/VIashunin/java-shareit/assets/114859572/6f5b0612-2441-4297-9a0f-99d3487947f2)
https://practicum.yandex.ru/trainer/java-developer/lesson/84640c8c-2bca-4678-bd6f-c6964ffae8de/?searchedText=ReflectionTestUtils

2023-06-19 18:56 UTC, VIashunin commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +        UserDto userDto = UserDto.builder().id(1L).name("User").email("user@yandex.ru").build();
Вынес user-а в метод @beforeeach

2023-06-20 19:09 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto addRequest(long userId, ItemRequestDto itemRequestDto) {
с одной стороны достаточно, но не очень хорошо, т.к. это может тормозить работу приложения, поскольку есть методы которые не обязательно выполнять в транзакции,

2023-06-20 19:10 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        ReflectionTestUtils.setField(bookingService, "itemService", itemService);
воу интересно, 
буду знать

2023-06-20 19:11 UTC, Fleaman777 approved these changes

2023-06-20 20:57 UTC, merged