feat: реализовать логику работы приложения согласно ТЗ16
VIashunin/java-shareit pull request #4
Opened 2023-07-03 20:30 UTC by VIashunin

2023-07-04 20:04 UTC, Fleaman777 requested changes

2023-07-04 20:04 UTC, Fleaman777 commented on docker-compose.yaml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2023-07-04 20:04 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
по джава код стайлу, константы должны иди перед обычными полями класса

2023-07-04 20:04 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода
меньше кода, меньше отвлекающих вещей

2023-07-04 20:04 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
здорово, правильная конструкция для просечивания энв переменных,
еще можно ее немного дополнить
spring.datasource.username=${POSTGRES_USER:postgres}
через двоеточие указывается значение, которое будет использоваться по умолчанию, если энв переменная не будет просечена

2023-07-05 15:21 UTC, VIashunin commented on docker-compose.yaml
> +    image: postgres:13.7-alpine
Спасибо за оценку

2023-07-05 15:24 UTC, VIashunin commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
Исправил

2023-07-05 15:29 UTC, VIashunin commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
удалил там, где нет необходимости в параметре name

2023-07-05 15:30 UTC, VIashunin commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
Спасибо за оценку
Дополнил значением по умолчанию согласно рекомендации

2023-07-05 19:04 UTC, Fleaman777 approved these changes

2023-07-05 19:06 UTC, merged